/*
 * Copyright (C) 2017 FirmaEC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ec.gob.firmadigital.firmador;


import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;

/**
 *
 * @author FirmaEC
 * @author Asamblea Nacional
 */
public class JPanellAcercaDe extends JPanel {
    
    //private static final Logger logger = Logger.getLogger(JPanellAcercaDe.class.getName());
    private static final String URL_GOBIERNO_DIGITAL = "http://www.gobiernoelectronico.gob.ec";
    private static final String URL_ASAMBLEA = "http://www.asambleanacional.gob.ec";

    /**
     * Creates new form jplAcercaDe
     */
    public JPanellAcercaDe() {
        initComponents();

        jlbUrlGobiernoDigitalAcercaDe.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    Desktop.getDesktop().browse(new URI(URL_GOBIERNO_DIGITAL));
                } catch (URISyntaxException | IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        lblUrlAsamblea.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    Desktop.getDesktop().browse(new URI(URL_ASAMBLEA));
                } catch (IOException | URISyntaxException e1) {
                    Logger.getLogger(JPanellAcercaDe.class.getName()).log(Level.SEVERE, null, e);
                }
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                if(Cursor.DEFAULT_CURSOR==getCursor().getType()) {
                    setCursor(new Cursor(Cursor.HAND_CURSOR));
                }
            }

            @Override
            public void mouseExited(MouseEvent e) {
                setCursor(Cursor.getDefaultCursor());
            }
        });

        Properties prop = new Properties();
        try {
            prop.load(getClass().getClassLoader().getResourceAsStream("config.properties"));
            this.jlbVersion.setText("Versión: " + prop.getProperty("version")+ " - " + prop.getProperty("fecha"));
        } catch (IOException ex) {
            Logger.getLogger(JPanellAcercaDe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        JLabel jlbCopyrightAcercaDe = new JLabel("Powered by: FirmaEC © Copyright MINTEL 2017");
        JLabel jlbLicenciaAcercaDe = new JLabel("Licencia GPLv3");
        jlbUrlGobiernoDigitalAcercaDe = new JLabel(URL_GOBIERNO_DIGITAL);
        jlbVersion = new JLabel();

        jlbCopyrightAcercaDe = new javax.swing.JLabel();
        jlbLicenciaAcercaDe = new javax.swing.JLabel();
        jlbUrlGobiernoDigitalAcercaDe = new javax.swing.JLabel();
        jlbVersion = new javax.swing.JLabel();

        lblUrlAsamblea= new JLabel(URL_ASAMBLEA);
        JLabel lblCopyrightAsamblea = new JLabel("© Asamblea Nacional 2018");

        BufferedImage bim = null;
        try {
            bim= ImageIO.read(ClassLoader.getSystemResource("images/logoAN.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        ImageIcon imgIcoLogo = new ImageIcon(bim);
        JLabel lblLogo = new JLabel(imgIcoLogo);


        BoxLayout layout = new BoxLayout(this, BoxLayout.Y_AXIS);
        this.setLayout(layout);

        lblLogo.setAlignmentX(Component.CENTER_ALIGNMENT);
        add(lblLogo);

        add(Box.createRigidArea(new Dimension(0,20)));
        lblCopyrightAsamblea.setAlignmentX(Component.CENTER_ALIGNMENT);
        add(lblCopyrightAsamblea);
        lblUrlAsamblea.setAlignmentX(Component.CENTER_ALIGNMENT);
        add(lblUrlAsamblea);

        add(Box.createRigidArea(new Dimension(0,20)));

        jlbCopyrightAcercaDe.setAlignmentX(Component.CENTER_ALIGNMENT);
        add(jlbCopyrightAcercaDe);

        jlbLicenciaAcercaDe.setAlignmentX(Component.CENTER_ALIGNMENT);
        add(jlbLicenciaAcercaDe);

        jlbUrlGobiernoDigitalAcercaDe.setAlignmentX(Component.CENTER_ALIGNMENT);
        add(jlbUrlGobiernoDigitalAcercaDe);

        jlbVersion.setAlignmentX(Component.CENTER_ALIGNMENT);
        add(jlbVersion);
    }// </editor-fold>//GEN-END:initComponents


    private javax.swing.JLabel jlbUrlGobiernoDigitalAcercaDe;
    private javax.swing.JLabel jlbVersion;
    private JLabel lblUrlAsamblea;
    // End of variables declaration//GEN-END:variables
}
